export const WELCOME_LINES: string[] = [
  "yo welcome back fucker, ready to go raw on this code?",
  "hell yeah you're back, let's rawdog some code",
  "no types, no tests, no safewords, ready to ship recklessly?",
  "it's raw hours baby, who needs a linter anyway",
  "look who crawled back, bet you missed going commando",
  "pull up a chair degenerate, let's break something beautiful",
  "miss me slut? let's defile some codebase",
  "the gang's all here, pants off keyboard out",
  "back for another round? hope you brought stamina",
  "welcome to the filth pit, we don't knock we kick doors",
  "you absolute menace, let's bully some bytes",
  "howdy partner, ready to rawdog main?",
  "hey slut missed you, forget the safety net",
  "ohh you're back, bet prod's nervous already",
  "clocked in degenerate mode, no mercy for the tech debt",
  "hope you warmed up, we're going balls deep today",
  "the freak has returned, let's make something questionable",
  "sup you beautiful disaster, code like nobody's watching",
  "welcome to sin city, population you and this repo",
  "lock the door, this is gonna get weird",
  "ready to raw? main branch said it's on",
  "engine's running pervert, let's merge without reading",
  "hey sweet thing, time to wreck some diffs",
  "you're nasty for this one, but the code won't write itself",
  "nice to see you freak, production fears your return",
  "get in loser, we're deleting node_modules",
  "oh thank god, someone needed to ship this garbage",
  "hi honey i'm home, also i brought segfaults",
  "back in the trenches, keep your helmet on",
  "the raw one cometh, kneel tests",
  "howdy cowboy, let's break the staging horse",
  "the prodigal slut returns, shall we sin in typescript?",
  "what's up freak, ready to commit straight to main?",
  "rise and grind hoe, standup was cancelled",
  "welcome home rat, the cheese is in the codebase",
  "you look unwell, perfect let's write python",
  "reporting for duty captain, no pants no problem",
  "hey stinker, let's make the reviewers cry",
  "welcome back you gremlin, time to goblin on this repo",
  "another day another felony, let's touch the database",
];

export function pickWelcome(): string {
  return WELCOME_LINES[Math.floor(Math.random() * WELCOME_LINES.length)]!;
}
